# Generated by Django 5.0.2 on 2024-03-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_remove_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ratings',
            field=models.CharField(default='', max_length=25),
        ),
    ]
