# Generated by Django 5.0.2 on 2024-03-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_feedback_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='ratings',
            new_name='rating',
        ),
    ]
