# Generated by Django 5.0.2 on 2024-03-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_rename_ratings_feedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
