# Generated by Django 5.0.1 on 2024-03-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_remove_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNR_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_number', models.CharField(max_length=10)),
                ('pnr_station', models.CharField(max_length=25)),
            ],
        ),
    ]
