# Generated by Django 5.0.1 on 2024-03-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_pnr_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PNR_Number',
            new_name='PnrNumber',
        ),
    ]
