# Generated by Django 5.0.1 on 2024-03-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_rename_pnr_number_pnrnumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PnrNumber',
            new_name='PnrGenerator',
        ),
    ]
