# Generated by Django 5.0.1 on 2024-03-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_rename_pnrnumber_pnrgenerator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnrgenerator',
            name='id',
        ),
        migrations.AlterField(
            model_name='pnrgenerator',
            name='pnr_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
