# Generated by Django 5.0.1 on 2024-03-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_movetrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movetrain',
            name='current_station',
            field=models.CharField(choices=[('TRV', 'Trivandrum'), ('KLM', 'Kollam')], default='', max_length=240),
        ),
    ]
