# Generated by Django 5.0.1 on 2024-03-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_alter_movetrain_current_station'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoveTrain',
        ),
    ]
