# Generated by Django 5.0.2 on 2024-02-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=25)),
                ('product_name', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=25)),
                ('date', models.DateField()),
            ],
        ),
    ]
