# Generated by Django 5.0.2 on 2024-02-21 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.customer'),
        ),
    ]
