# Generated by Django 5.0.2 on 2024-02-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_order_train_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='train_number',
            field=models.IntegerField(),
        ),
    ]
