# Generated by Django 5.0.2 on 2024-02-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_order_train_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='train_number',
        ),
    ]
