# Generated by Django 5.0.1 on 2024-02-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_order_customer_name_remove_order_train_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='order',
            name='train_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
