# Generated by Django 5.0.1 on 2024-02-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='train_number',
            field=models.CharField(max_length=10),
        ),
    ]
