# Generated by Django 5.0.2 on 2024-03-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
