# Generated by Django 5.0.1 on 2024-03-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_remove_customer_pnr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pnr_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
