# Generated by Django 5.0.1 on 2024-03-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_customer_pnr_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pnr_number',
        ),
    ]
