# Generated by Django 5.0.1 on 2024-04-01 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_order_pre_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pre_order',
            new_name='pre_order_date',
        ),
    ]
