# Generated by Django 5.0.1 on 2024-04-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_rename_pre_order_order_pre_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pre_order_date',
            field=models.CharField(default='NA', max_length=200, null=True),
        ),
    ]
