# Generated by Django 5.0.1 on 2024-04-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_alter_order_pre_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_train_number', models.CharField(default='', max_length=10)),
                ('pre_customer_name', models.CharField(default='', max_length=25)),
                ('pre_product_name', models.CharField(default='', max_length=25)),
                ('pre_price', models.CharField(default='', max_length=25)),
                ('pre_date', models.DateField(auto_now_add=True)),
                ('pre_pre_order_date', models.CharField(default='NA', max_length=200, null=True)),
            ],
        ),
    ]
