# Generated by Django 5.0.1 on 2024-04-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_preorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreOrder',
        ),
    ]
