# Generated by Django 5.0.2 on 2024-02-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_password',
            field=models.CharField(default='vendor', max_length=25),
        ),
    ]
