# Generated by Django 5.0.2 on 2024-02-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0005_alter_vendor_vendor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='food_availability',
        ),
    ]
