# Generated by Django 5.0.2 on 2024-02-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0006_remove_fooditem_food_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
