# Generated by Django 5.0.2 on 2024-02-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0007_fooditem_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
