# Generated by Django 5.0.2 on 2024-02-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0009_alter_fooditem_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_description',
            field=models.CharField(max_length=20),
        ),
    ]
