# Generated by Django 5.0.2 on 2024-02-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0011_alter_fooditem_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='food_description',
            new_name='food_category',
        ),
    ]
