# Generated by Django 5.0.2 on 2024-02-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0012_rename_food_description_fooditem_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='vendor',
        ),
    ]
