# Generated by Django 5.0.2 on 2024-02-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0013_remove_fooditem_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
