# Generated by Django 5.0.1 on 2024-03-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0015_alter_fooditem_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='resturant_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
