# Generated by Django 5.0.1 on 2024-03-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0016_fooditem_resturant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='station_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
