# Generated by Django 5.0.1 on 2024-04-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0017_fooditem_station_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='vendor_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
